### ISSUE TITLE
Is it possible to use gwtchosen as searchbox for multiple custom search terms?

### ISSUE THREAD

**Issue by luxmar** [ArcBees/gwtchosen#282] opened 2015-10-21 17:14 UTC
I want to use gwtchosen 3.x as serachbox for muliple search terms. If a search term is inside the list, it should show up. But if the term isn't in the list, it should be added to to the searchbox.

Here is an example: In the example for "Multiple select with groups" the user can select multiple terms from the stored list. But if the user enters a new unknown term, the widget shows only "No results match for custom term"
Would it be possible to add the same behaviour for custom terms as for stored terms if the user presses enter? => a new term entry with X to delete should appear inside the searchbox.

This would give the image the possibility to be a first class custom serachbox with suggestions. 

![bildschirmfoto vom 2015-10-21 19 03 57](https://cloud.githubusercontent.com/assets/7394438/10644124/094076e6-7827-11e5-9827-51cebda421cc.png)

Is the described behaviour possible with gwtchosen 3.x? Or could you make a new feature for this? Or do you know a workaround how to implement this for my own?

Thanks in advance!

**Comment by meriouma** [comment] 2015-10-27 05:52
Sorry, GWT Chosen doesn't support this at the moment. We might consider adding this in the future. In the meantime, you might want to have a look at SuggestBox and SuggestOracle

**Comment by meriouma** [comment] 2015-10-27 17:43
Duplicate of #37

**Closed by meriouma** 2015-10-27 17:43 UTC
